services:
  - type: web
    name: exoplanet-classifier
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PYTHONUNBUFFERED
        value: 1
      - key: VITE_API_URL
        value: /api
