services:
  - type: web
    name: exoplanet-classifier
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter  # Starter plan ($7/month) - eliminates cold starts and provides better resources
    healthCheckPath: /
    healthCheckTimeout: 300
    envVars:
      - key: PYTHONPATH
        value: /app
      - key: PYTHONUNBUFFERED
        value: 1
      - key: VITE_API_URL
        value: /api
      - key: RENDER
        value: true
